# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
    terraform {
        required_providers {
            kubernetes = {
                source = "hashicorp/kubernetes"
                version = "2.23.0"
            }
        }
        required_version = "1.5.6"
    }
    provider "kubernetes" {
        config_path = "~/.kube/config"
        config_context = "minikube"
    }


